const PDFDocument = require('pdfkit');

const generateResumePDF = (profileData) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const primaryColor = '#6366f1';
      const darkColor = '#1f2937';
      const grayColor = '#6b7280';
      const lightGray = '#f3f4f6';

      doc.rect(0, 0, doc.page.width, 120).fill(primaryColor);

      doc.fontSize(28).fillColor('white').font('Helvetica-Bold')
        .text(profileData.name || 'Student Name', 50, 35);
      doc.fontSize(14).fillColor('rgba(255,255,255,0.85)').font('Helvetica')
        .text(profileData.branch || 'Computer Science Engineering', 50, 68);

      let contactParts = [];
      if (profileData.email) contactParts.push(`✉ ${profileData.email}`);
      if (profileData.phone) contactParts.push(`☎ ${profileData.phone}`);
      if (profileData.linkedin) contactParts.push(`in ${profileData.linkedin}`);

      doc.fontSize(10).fillColor('rgba(255,255,255,0.75)')
        .text(contactParts.join('   |   '), 50, 93);

      let yPos = 145;

      const addSection = (title) => {
        doc.moveTo(50, yPos).lineTo(545, yPos).strokeColor(primaryColor).lineWidth(2).stroke();
        yPos += 8;
        doc.fontSize(13).fillColor(primaryColor).font('Helvetica-Bold').text(title, 50, yPos);
        yPos += 22;
      };

      const addBullet = (text) => {
        doc.fontSize(10).fillColor(darkColor).font('Helvetica')
          .text(`• ${text}`, 65, yPos, { width: 480 });
        yPos += doc.heightOfString(text, { width: 480 }) + 6;
      };

      addSection('EDUCATION');
      doc.rect(50, yPos - 4, 495, 55).fill(lightGray).stroke('#e5e7eb');
      doc.fontSize(12).fillColor(darkColor).font('Helvetica-Bold')
        .text(profileData.collegeName || 'Your College Name', 60, yPos + 2);
      doc.fontSize(10).fillColor(grayColor).font('Helvetica')
        .text(`${profileData.branch || 'B.Tech CSE'}   |   Semester ${profileData.semester || 'N/A'}`, 60, yPos + 18);
      doc.fontSize(11).fillColor(primaryColor).font('Helvetica-Bold')
        .text(`CGPA: ${profileData.cgpa || 'N/A'}`, 420, yPos + 2);
      doc.fontSize(10).fillColor(grayColor).font('Helvetica')
        .text(`Reg. No: ${profileData.regNumber || 'N/A'}`, 420, yPos + 18);
      yPos += 68;

      if (profileData.skills && profileData.skills.length > 0) {
        addSection('TECHNICAL SKILLS');
        const chunkSize = 5;
        for (let i = 0; i < profileData.skills.length; i += chunkSize) {
          const chunk = profileData.skills.slice(i, i + chunkSize).join('   •   ');
          doc.fontSize(10).fillColor(darkColor).font('Helvetica')
            .text(chunk, 55, yPos);
          yPos += 18;
        }
        yPos += 8;
      }

      if (profileData.projects && profileData.projects.length > 0) {
        addSection('PROJECTS');
        profileData.projects.slice(0, 3).forEach((project) => {
          doc.fontSize(11).fillColor(darkColor).font('Helvetica-Bold')
            .text(`▸ ${project.title}`, 55, yPos);
          yPos += 16;
          if (project.techStack && project.techStack.length > 0) {
            doc.fontSize(9).fillColor(primaryColor).font('Helvetica-Bold')
              .text(`Tech Stack: ${project.techStack.join(', ')}`, 65, yPos);
            yPos += 14;
          }
          if (project.description) {
            doc.fontSize(10).fillColor(grayColor).font('Helvetica')
              .text(project.description, 65, yPos, { width: 470 });
            yPos += doc.heightOfString(project.description, { width: 470 }) + 10;
          }
        });
      }

      if (profileData.achievements && profileData.achievements.length > 0) {
        addSection('ACHIEVEMENTS & CERTIFICATIONS');
        profileData.achievements.forEach((ach) => addBullet(ach));
      }

      if (profileData.certifications && profileData.certifications.length > 0) {
        if (!(profileData.achievements && profileData.achievements.length > 0)) {
          addSection('CERTIFICATIONS');
        }
        profileData.certifications.forEach((cert) => {
          addBullet(`${cert.name} - ${cert.issuer} (${cert.year})`);
        });
      }

      const footerY = doc.page.height - 40;
      doc.rect(0, footerY - 10, doc.page.width, 50).fill(lightGray);
      doc.fontSize(9).fillColor(grayColor)
        .text('Generated by PlacementPro | Your Career Launchpad', 50, footerY, { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateResumePDF };
